AllCops:
  Exclude:
    - db/**

ClassLength:
  CountComments: false  # count full line comments?
  Max: 100

LineLength:
  Enabled: true
  Max: 79

MethodLength:
  CountComments: false  # count full line comments?
  Max: 5

ParameterLists:
  Max: 4
  CountKeywordArgs: true

TrailingWhitespace:
  Enabled: true
