#!/bin/bash

sudo aptitude update
sudo aptitude install \
  autoconf \
  automake \
  bash \
  bikeshed \
  bison \
  build-essential \
  curl \
  elinks-lite \
  git \
  git-core \
  htop \
  imagemagick \
  libc6-dev \
  libcurl4-openssl-dev \
  libffi-dev \
  libfreeimage-dev \
  libgdbm-dev \
  libimobiledevice-dev \
  libmagick++-dev \
  libmagickcore-dev \
  libmagickwand-dev \
  libmysqlclient-dev \
  libncurses5 \
  libncurses5-dev \
  libopenmpi-dev \
  libplist++-dev \
  libplist-dev \
  libpq-dev \
  libreadline6 \
  libreadline6-dev \
  libsqlite3-dev \
  libssl-dev \
  libtool \
  libusb-1.0-0-dev \
  libusb-dev \
  libxml2-dev \
  libxslt-dev \
  libxslt1-dev \
  libyaml-dev \
  lnav \
  lynx \
  mc \
  mediainfo \
  ncurses-dev \
  nmap \
  nodejs \
  openjdk-7-jre \
  openmpi-bin \
  openssh-client \
  openssh-server \
  openssl \
  p7zip \
  phantomjs \
  pkg-config \
  postgresql \
  postgresql-contrib \
  rar \
  redis-server \
  screen \
  sqlite3 \
  subversion \
  tcl-dev \
  unrar \
  usbmuxd \
  vim \
  wget \
  zip \
  zlib1g \
  zlib1g-dev \
  zsh \
  zsh-lovers

