#!/bin/bash

sudo apt update
sudo apt install \
  autoconf \
  automake \
  bash \
  bikeshed \
  bison \
  build-essential \
  curl \
  elinks \
  exfat-fuse \
  exfat-utils \
  gconf-service \
  git \
  git-core \
  git-flow \
  htop \
  imagemagick \
  libappindicator1 \
  libc6-dev \
  libcurl4-openssl-dev \
  libffi-dev \
  libfreeimage-dev \
  libgconf-2-4 \
  libgdbm-dev \
  libimobiledevice-dev \
  libmagick++-dev \
  libmagickcore-dev \
  libmagickwand-dev \
  libmysqlclient-dev \
  libncurses5 \
  libncurses5-dev \
  libopenmpi-dev \
  libplist++-dev \
  libplist-dev \
  libpq-dev \
  libreadline7 \
  libreadline-dev \
  libsqlite3-dev \
  libssl-dev \
  libtool \
  libusb-1.0-0-dev \
  libusb-dev \
  libxml2-dev \
  libxslt1-dev \
  libyaml-dev \
  lnav \
  lynx \
  mc \
  mediainfo \
  nmap \
  nodejs \
  openjdk-9-jre \
  openmpi-bin \
  openssh-client \
  openssh-server \
  openssl \
  p7zip \
  phantomjs \
  pkg-config \
  postgresql \
  postgresql-contrib \
  rar \
  redis-server \
  screen \
  sqlite3 \
  subversion \
  tcl-dev \
  unrar \
  usbmuxd \
  vim \
  wget \
  zip \
  zlib1g \
  zlib1g-dev \
  zsh \
  libappindicator1 \
  gconf-service \
  libgconf-2-4 \
  zsh-lovers
