#!/bin/bash

sudo aptitude update
sudo aptitude install \
  autoconf \
  automake \
  bash \
  bison \
  build-essential \
  curl \
  elinks-lite \
  git \
  git-core \
  htop \
  imagemagick \
  libc6-dev \
  libcurl4-openssl-dev \
  libffi-dev \
  libfreeimage-dev \
  libgdbm-dev \
  libmagick++-dev \
  libmagickcore-dev \
  libmagickwand-dev \
  libmysql-ruby \
  libmysqlclient-dev \
  libncurses5 \
  libncurses5-dev \
  libopenmpi-dev \
  libpq-dev \
  libreadline6 \
  libreadline6-dev \
  libsqlite3-dev \
  libssl-dev \
  libtool \
  libxml2-dev \
  libxslt-dev \
  libxslt1-dev \
  libyaml-dev \
  lynx \
  mc \
  ncurses-dev \
  nmap \
  openjdk-7-jre \
  openmpi-bin \
  openssh-client \
  openssh-server \
  openssl \
  p7zip \
  pkg-config \
  phantomjs \
  rar \
  screen \
  sqlite3 \
  subversion \
  tcl-dev \
  unrar \
  vim \
  wget \
  zip \
  zlib1g \
  zlib1g-dev \
  zsh \
  zsh-lovers
